services:
  ips:
    image: ips:latest
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: ips
    restart: unless-stopped
    ports:
      - '9999:9999'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - HOST=0.0.0.0
      - PORT=9999
      - LOG_LEVEL=DEBUG
      - DB_DRIVER=postgresql
      - DB_USERNAME=tfm
      - DB_PASSWORD=tfm
      - DB_HOST=ips_db
      - DB_PORT=5432
      - DB_NAME=ips
    volumes:
      - ../scripts/setup_db.sh:/app/scripts/setup_db.sh
  
  db:
    image: postgres:latest
    container_name: ips_db
    restart: always
    environment:
      - POSTGRES_USER=tfm
      - POSTGRES_PASSWORD=tfm
      - POSTGRES_DB=ips
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tfm"]
      interval: 10s
      timeout: 3s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ips_pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=tfm@tfm.com
      - PGADMIN_DEFAULT_PASSWORD=tfm
      - PGADMIN_LISTEN_PORT=80
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '5050:80'
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  db:
    driver: local
  pgadmin:
    driver: local