"""add all models

Revision ID: 11072e999dd9
Revises: 
Create Date: 2024-07-24 14:43:02.134800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11072e999dd9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('acquisition_campaigns',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('scenario', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.username'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_acquisition_campaigns_name'), 'acquisition_campaigns', ['name'], unique=False)
    op.create_table('acquisition_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('preamble_time', sa.Integer(), nullable=True),
    sa.Column('acquisition_time', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_name'], ['acquisition_campaigns.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acquisition_points_id'), 'acquisition_points', ['id'], unique=False)
    op.create_table('point_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('beacon', sa.Integer(), nullable=False),
    sa.Column('rssi', sa.Integer(), nullable=False),
    sa.Column('tx_time_ns', sa.String(), nullable=True),
    sa.Column('rx_time_ns', sa.String(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['point_id'], ['acquisition_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_samples_id'), 'point_samples', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_point_samples_id'), table_name='point_samples')
    op.drop_table('point_samples')
    op.drop_index(op.f('ix_acquisition_points_id'), table_name='acquisition_points')
    op.drop_table('acquisition_points')
    op.drop_index(op.f('ix_acquisition_campaigns_name'), table_name='acquisition_campaigns')
    op.drop_table('acquisition_campaigns')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
